commented out the autocomplete form
causing errors with Algolia. Uncaught TypeError: this.props.contextValue.store.getState is not a function. See: https://github.com/algolia/react-instantsearch/issues/2897