readd fix "MarkCompactCollector" "JavaScript heap out of memory" removed in cf07e1cebcc68a9f628447fb04d261c40eb0f338
see: https://github.com/ademidun/atila-client-web-app/commit/cf07e1cebcc68a9f628447fb04d261c40eb0f338
https://app.circleci.com/pipelines/github/ademidun/atila-client-web-app/1814/workflows/85d14deb-646e-47f9-b99a-416d2e536127/jobs/3422

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

https://stackoverflow.com/a/38560292/5405197