installed core-js 'npm' package because ScholarshipsList.test.js cannot find module 'core-js/stable' from 'ScholarshipsList.test.js'
https://app.circleci.com/pipelines/github/ademidun/atila-client-web-app/629/workflows/f719b4bc-0623-4637-afa7-c0990b3c26fd/jobs/1203

 FAIL  src/scenes/Scholarship/ScholarshipsList.test.js
  ● Test suite failed to run

    Cannot find module 'core-js/stable' from 'ScholarshipsList.test.js'

      2 | import {configure, shallow} from 'enzyme';
      3 | import Adapter from 'enzyme-adapter-react-16';
    > 4 | import "core-js/stable"; // needed otherwise .finally in promise does not work
        | ^
      5 |
      6 |
      7 | import ScholarshipsList from './ScholarshipsList';

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (src/scenes/Scholarship/ScholarshipsList.test.js:4:1)